CREATE TABLE IF NOT EXISTS `applications` (
	`id` VARCHAR(36) NOT NULL,
	`name` VARCHAR(36) NOT NULL,
	`description` VARCHAR(36) NOT NULL,
	`status` VARCHAR(36) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created_by` VARCHAR(36) NOT NULL,
	`updated_by` VARCHAR(36) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `apis` (
	`id` VARCHAR(36) NOT NULL,
	`name` VARCHAR(36) NOT NULL,
	`description` VARCHAR(36) NOT NULL,
	`status` VARCHAR(36) NOT NULL,
	`application_id` VARCHAR(36) NOT NULL,
	`endpoint` VARCHAR(36) NOT NULL,
	`mandatory_query_params` VARCHAR(36) NOT NULL,
	`optional_query_params` VARCHAR(36) NOT NULL,
	`response_format` VARCHAR(36) NOT NULL,
	`service_id` VARCHAR(36) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created_by` VARCHAR(36) NOT NULL,
	`updated_by` VARCHAR(36) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;
